In [1]:
import numpy as np

## Datatypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.5,3], [4,5,6.5]])

In [5]:
a2

array([[1. , 2.5, 3. ],
       [4. , 5. , 6.5]])

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a1.ndim, a2.ndim

(1, 2)

In [9]:
a1.dtype, a2.dtype

(dtype('int64'), dtype('float64'))

In [10]:
a1.size, a2.size

(3, 6)

In [11]:
type(a1), type(a2)

(numpy.ndarray, numpy.ndarray)

In [12]:
# Create a dataframe from numpy array
import pandas as pd

df = pd.DataFrame(a2)

In [13]:
df

0    1    2
0  1.0  2.5  3.0
1  4.0  5.0  6.5

In [14]:
a3 = ([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [15]:
df2 = pd.DataFrame(a3)
df2

0             1             2
0     [1, 2, 3]     [4, 5, 6]     [7, 8, 9]
1  [10, 11, 12]  [13, 14, 15]  [16, 17, 18]

## Creating arrays

In [16]:
sample_array = np.array([1,2,3])

In [17]:
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype


dtype('int64')

In [19]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
type(ones)

numpy.ndarray

In [22]:
zeros = np.zeros((2,3))

In [23]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [25]:
random_array = np.random.randint(1000, 10000, size=(3,5))
random_array

array([[9764, 5161, 5318, 4588, 8816],
       [5468, 2680, 1313, 8083, 4301],
       [5596, 2396, 1650, 7343, 6075]])

In [26]:
random_array.size

15

In [27]:
random_array.shape

(3, 5)

In [28]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.68933288, 0.7999548 , 0.26299233],
       [0.60189377, 0.29488393, 0.61786228],
       [0.02680051, 0.58465429, 0.39214706],
       [0.87528203, 0.22228713, 0.87407627],
       [0.39125235, 0.3910634 , 0.47293647]])

In [29]:
random_array_2.shape


(5, 3)

In [30]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.26699555, 0.0623271 , 0.93230957],
       [0.54999625, 0.09859939, 0.87664922],
       [0.78588612, 0.08017669, 0.21753994],
       [0.26744547, 0.85992982, 0.98536413],
       [0.54616686, 0.67606167, 0.08711422]])

In [31]:
# Pseudo-random numbers
np.random.seed()

In [32]:
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[9, 3, 9],
       [2, 2, 2],
       [9, 5, 1],
       [4, 9, 8],
       [0, 0, 7]])

In [33]:
random_array_4.shape

(5, 3)

## Viewing arrays & matrices

In [34]:
random_array_4

array([[9, 3, 9],
       [2, 2, 2],
       [9, 5, 1],
       [4, 9, 8],
       [0, 0, 7]])

In [35]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 7, 8, 9])

## Manipulating & Comparing arrays

### Artithmetic 

In [36]:
a1

array([1, 2, 3])

In [37]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
ones = np.ones(3)

In [39]:
ones

array([1., 1., 1.])

In [40]:
a1 + ones

array([2., 3., 4.])

In [41]:
a1 - ones

array([0., 1., 2.])

In [42]:
a1 * ones

array([1., 2., 3.])

In [43]:
a2

array([[1. , 2.5, 3. ],
       [4. , 5. , 6.5]])

In [44]:
a1 * a2

array([[ 1. ,  5. ,  9. ],
       [ 4. , 10. , 19.5]])

In [45]:
a3

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]

In [46]:
# How can you reshape a2 to be comaptiable with a3?
# Search: How to reshape numpy array?
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a1/ones

In [ ]:
a2 / a1

In [ ]:
# Floor
a2 // a1

In [ ]:
a2 ** 2

In [ ]:
a % 2

In [ ]:
a1 % 2

In [ ]:
np.mod(a1, 2)

In [ ]:
np.mod(a2, 2)

In [ ]:
np.exp(a1)

In [ ]:
np.log(a1)

### Aggregation

In [ ]:
listy_list = [1,2,3]
type(listy_list)

In [ ]:
sum(listy_list)

In [ ]:
a1

In [ ]:
type(a1)

In [ ]:
np.sum(a1)

# Use Python's methods on Python data types and use
# Numpy's methods on NumPy Arrays

In [ ]:
# Create a massive NumPy Array
massive_array = np.random.random(100000)
massive_array.size

In [ ]:
massive_array[:10]

In [ ]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)

In [ ]:
np.min(a2)

In [ ]:
# Standard deviation = squareroot of variance
np.std(a2)

In [ ]:
# Variance = measure of the average degree to which each number is different
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

In [ ]:
# Demo of std and var
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show()

### Reshaping and transposing

In [ ]:
a2.shape

In [ ]:
a2 * a3

In [ ]:
a2.reshape(2,3,1).shape

In [ ]:
a2.shape

In [ ]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

In [ ]:
a2_reshape * a3

In [ ]:
# Transpose
a2.T

In [ ]:
a2.T.shape

In [ ]:
a3.shape

In [ ]:
a3

In [ ]:
a3.T.shape

## Dot product

In [ ]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

mat1

In [ ]:
mat2

In [ ]:
mat1.shape, mat2.shape

In [ ]:
# Element wise multiplication Hadamard product
mat1 * mat2

In [ ]:
# Dot product
np.dot(mat1, mat2)

In [ ]:
# Transpose mat1
mat1.T

In [ ]:
mat2.shape, mat1.T.shape

In [ ]:
mat3 = np.dot(mat1, mat2.T)
mat3

In [ ]:
mat3.shape

## Dot product example ( nut butter sales )

In [ ]:
np.random.seed(0)
sales_amount = np.random.randint(20, size=(5,3))
sales_amount

In [ ]:
# Create weekly sales dataframe
weekly_sales = pd.DataFrame(sales_amount, index=["Mon", "Tues", "Web", "Thurs", "Fri"], columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])
weekly_sales

In [ ]:
# Create prices array
prices = np.array([10,8,12])
prices

In [ ]:
# Create butter prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["Price"], columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])
butter_prices

In [ ]:
total_sales = prices.dot(sales_amount)

In [ ]:
# Transpose, shapes are not aligned
total_sales = prices.dot(sales_amount.T)

In [ ]:
total_sales

In [ ]:
# Create daily sales
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

In [ ]:
weekly_sales["Total ($)"] = daily_sales
weekly_sales

In [ ]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

## Comparision operators

In [ ]:
a1

In [ ]:
a2

In [ ]:
a1 > a2

In [ ]:
a1 >= a2

In [ ]:
bool_array = a1 >= a2
bool_array

In [ ]:
a1 > 5

In [ ]:
a1 < 5

In [ ]:
a1 == a1

In [ ]:
a1 == a2

## Sorting arrays

In [ ]:
random_array

In [ ]:
random_array = np.random.randint(10, size=(3,5))

In [ ]:
random_array

In [ ]:
np.sort(random_array)

In [ ]:
np.argsort(random_array)

In [ ]:
np.argsort(a1)

In [ ]:
np.argmin(a1)

In [ ]:
np.argmin(random_array)

In [ ]:
np.argmax(random_array)

## Practical example - NumPy in action

In [47]:
<img src="panda.jpeg" />

SyntaxError: invalid syntax (1641079129.py, line 1)

In [49]:
<img src="panda.jpeg"/>

SyntaxError: invalid syntax (2683252691.py, line 1)

In [50]:
# Turn an image into a NumPy array
from matplotlib.image import imread

panda = imread("panda.jpeg")
print(type(panda))

<class 'numpy.ndarray'>


In [51]:
panda

array([[[ 95, 100,  70],
        [ 96, 101,  71],
        [ 98, 105,  74],
        ...,
        [ 85,  81,  56],
        [ 84,  80,  55],
        [ 83,  79,  54]],

       [[ 97, 102,  72],
        [ 96, 103,  72],
        [ 97, 104,  71],
        ...,
        [ 83,  79,  54],
        [ 84,  80,  55],
        [ 85,  81,  56]],

       [[ 98, 105,  74],
        [ 97, 104,  71],
        [ 96, 103,  70],
        ...,
        [ 73,  69,  44],
        [ 75,  71,  46],
        [ 77,  73,  48]],

       ...,

       [[151, 158, 104],
        [155, 162, 110],
        [154, 162, 113],
        ...,
        [ 52,  58,  14],
        [ 57,  63,  19],
        [ 60,  66,  22]],

       [[147, 154, 102],
        [149, 156, 105],
        [145, 153, 104],
        ...,
        [ 57,  58,  14],
        [ 61,  62,  18],
        [ 62,  63,  19]],

       [[145, 149,  98],
        [144, 151, 100],
        [139, 147, 100],
        ...,
        [ 71,  70,  26],
        [ 67,  66,  22],
        [ 58,  57,  13]]

In [52]:
panda.size, panda.shape, panda.ndim

(2880000, (600, 1600, 3), 3)

In [53]:
panda[:100]

array([[[ 95, 100,  70],
        [ 96, 101,  71],
        [ 98, 105,  74],
        ...,
        [ 85,  81,  56],
        [ 84,  80,  55],
        [ 83,  79,  54]],

       [[ 97, 102,  72],
        [ 96, 103,  72],
        [ 97, 104,  71],
        ...,
        [ 83,  79,  54],
        [ 84,  80,  55],
        [ 85,  81,  56]],

       [[ 98, 105,  74],
        [ 97, 104,  71],
        [ 96, 103,  70],
        ...,
        [ 73,  69,  44],
        [ 75,  71,  46],
        [ 77,  73,  48]],

       ...,

       [[ 94, 100,  56],
        [ 91,  97,  53],
        [ 89,  96,  54],
        ...,
        [ 66,  62,  35],
        [ 61,  56,  27],
        [ 58,  53,  24]],

       [[ 92, 101,  58],
        [ 90,  99,  56],
        [ 90,  99,  56],
        ...,
        [ 65,  61,  32],
        [ 61,  56,  27],
        [ 54,  49,  20]],

       [[ 92, 100,  59],
        [ 89, 100,  58],
        [ 90, 101,  61],
        ...,
        [ 63,  59,  30],
        [ 66,  61,  31],
        [ 60,  55,  25]]

In [54]:
panda[:5]

array([[[ 95, 100,  70],
        [ 96, 101,  71],
        [ 98, 105,  74],
        ...,
        [ 85,  81,  56],
        [ 84,  80,  55],
        [ 83,  79,  54]],

       [[ 97, 102,  72],
        [ 96, 103,  72],
        [ 97, 104,  71],
        ...,
        [ 83,  79,  54],
        [ 84,  80,  55],
        [ 85,  81,  56]],

       [[ 98, 105,  74],
        [ 97, 104,  71],
        [ 96, 103,  70],
        ...,
        [ 73,  69,  44],
        [ 75,  71,  46],
        [ 77,  73,  48]],

       [[ 96, 106,  72],
        [ 95, 105,  71],
        [ 94, 104,  69],
        ...,
        [ 64,  60,  35],
        [ 63,  61,  36],
        [ 64,  62,  37]],

       [[ 94, 106,  70],
        [ 93, 105,  69],
        [ 95, 105,  70],
        ...,
        [ 64,  60,  35],
        [ 60,  58,  33],
        [ 59,  57,  32]]], dtype=uint8)

In [55]:
<img src="panda.jpeg"/>

SyntaxError: invalid syntax (2683252691.py, line 1)

In [56]:
car = imread("car.jpeg")

In [57]:
car

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [58]:
dog = imread("dog.jpeg")

In [59]:
dog

array([[[20, 33, 16],
        [20, 33, 16],
        [20, 31, 15],
        ...,
        [78, 65, 56],
        [77, 64, 55],
        [77, 64, 55]],

       [[21, 34, 17],
        [22, 33, 17],
        [22, 33, 17],
        ...,
        [80, 67, 58],
        [79, 66, 57],
        [79, 66, 57]],

       [[24, 35, 19],
        [23, 34, 18],
        [23, 34, 18],
        ...,
        [84, 71, 62],
        [82, 69, 60],
        [81, 68, 59]],

       ...,

       [[66, 63, 44],
        [66, 63, 44],
        [66, 63, 44],
        ...,
        [50, 40, 38],
        [50, 40, 38],
        [50, 40, 38]],

       [[66, 63, 44],
        [67, 64, 45],
        [67, 64, 45],
        ...,
        [50, 40, 38],
        [50, 40, 38],
        [50, 40, 38]],

       [[66, 63, 44],
        [66, 63, 44],
        [67, 64, 45],
        ...,
        [52, 42, 40],
        [52, 42, 40],
        [53, 43, 41]]], dtype=uint8)