In [1]:
import numpy as np

## Datatypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2.5,3], [4,5,6.5]])

In [7]:
a2

array([[1. , 2.5, 3. ],
       [4. , 5. , 6.5]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a1.ndim, a2.ndim

(1, 2)

In [11]:
a1.dtype, a2.dtype

(dtype('int64'), dtype('float64'))

In [12]:
a1.size, a2.size

(3, 6)

In [13]:
type(a1), type(a2)

(numpy.ndarray, numpy.ndarray)

In [14]:
# Create a dataframe from numpy array
import pandas as pd

df = pd.DataFrame(a2)

In [15]:
df

0    1    2
0  1.0  2.5  3.0
1  4.0  5.0  6.5

In [16]:
a3 = ([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [17]:
df2 = pd.DataFrame(a3)
df2

0             1             2
0     [1, 2, 3]     [4, 5, 6]     [7, 8, 9]
1  [10, 11, 12]  [13, 14, 15]  [16, 17, 18]

## Creating arrays

In [19]:
sample_array = np.array([1,2,3])

In [20]:
sample_array

array([1, 2, 3])

In [21]:
sample_array.dtype


dtype('int64')

In [22]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
ones.dtype

dtype('float64')

In [24]:
type(ones)

numpy.ndarray

In [25]:
zeros = np.zeros((2,3))

In [26]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [28]:
random_array = np.random.randint(1000, 10000, size=(3,5))
random_array

array([[6896, 9684, 9871, 6944, 6063],
       [4458, 9051, 6276, 8146, 8873],
       [7714, 5311, 4530, 6902, 5812]])

In [29]:
random_array.size

15

In [30]:
random_array.shape

(3, 5)

In [32]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.32857151, 0.90869438, 0.23006604],
       [0.16161976, 0.65429458, 0.98275328],
       [0.69885431, 0.95009916, 0.67822904],
       [0.21921133, 0.91428184, 0.08113649],
       [0.17539146, 0.76846647, 0.60503846]])

In [33]:
random_array_2.shape


(5, 3)

In [34]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.47727326, 0.15437548, 0.53191594],
       [0.4068305 , 0.70980681, 0.17688541],
       [0.5664657 , 0.01174329, 0.78820208],
       [0.35743588, 0.99569341, 0.15047029],
       [0.06108201, 0.13782345, 0.56958319]])

In [35]:
# Pseudo-random numbers
np.random.seed()